### ISSUE TITLE
Parameterize normals in terms of variance than rather sd?

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#20]
Pros: matches up with mathematical notation
Cons: deviates from base R

**Comment by 1danjordan** [comment]
This always confused me in exams using stats tables to lookup Z-scores! I'd be hesitant to deviate from the standard mathematical notation, but the precedent has already been set in base R, so I think it is wiser to stick with standard deviations. I think we think and reason about distributions in standard deviations rather than variances, because it is in the same scale of the data. So this might make it easier for learners.

**Comment by statibk** [comment]
You could allow both in the `Normal()` constructor and standardize internally. Base R does the same in some places, see e.g. `?NegBinomial`, which can be parameterized in terms of either `p` or `mu` (plus `size` in both cases).

BTW: Your `NegativeBinomial()` constructor currently only allows for the parameterization with `p` but not `mu` which would be inconvenient when used in combination with `glm.nb()` and related regression tools.

**Comment by alexpghayes** [comment]
`distr6` handles this kind of thing nicely, see their approach if this important to you as a user. We'll punt on this here since maintenance mode.
