### ISSUE TITLE
Multivariate distributions

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#21]
- Probably need their own subclass of `distributions`
- Ugh. What should the return be? Traditionally R has return a matrix with no row or column names, which is really irritating if you want to put things into a tibble right after. I think a matrix with column names? cc @1danjordan @EmilHvitfeldt

Distributions to start with
- Categorical
- Multinomial
- Multivariate Normal

**Comment by 1danjordan** [comment]
Do you want new constructors or do you want to infer the univariate/multivariate from the inputs? `MVNormal(c(0, .5, -.5), c(1, 2, 3))`  vs `Normal(c(0, .5, -.5), c(1, 2, 3))`. This is really where multiple dispatch in Julia thrives. 

For the names of the matrix columns, are they to be named by convention (`X1`, `X2`, `...`), passed in as an argument or taken from the names of the parameter vectors passed?

```r
# inherited from named vector
X <- Normal(c(a = 0, b = 1, c = 11), c(3, 1, 2))

# passed as argument
X <- Normal(c(0, 1, 11), (3, 1, 2), dim_names = c("a", "b", "c")
```

**Comment by EmilHvitfeldt** [comment]
> `MVNormal` vs `Normal`?

I would argue having different names for multivariate distributions. 
Having one function being able to do multiple things could be complicated for new users. Especially since the output format would be vector or matrix depending on input.
Documentation would be easier to read if univariate and multivariate are separated (with links between related of course).
At least in my mind, I see multivariate and univariate distributions are being different "beasts" and should be separate.

I vote for matrix with column names.

I would have them inherited from named vector

```r
X <- Normal(c(a = 0, b = 1, c = 11), c(3, 1, 2))
```

with warning and name-repair for partly unnamed vectors. Completely unnamed vectors should be `X1, X2, ...`.

**Comment by 1danjordan** [comment]
I agree regarding `MVNormal` vs `Normal`. There is something elegant about considering a univariate distribution as just the 1-dimensional case of a distribution, but 99% of time you want a univariate and multivariate is the edge case. Being explicit will prevent hard to catch mistakes and ensure the type stability of the return type. Univariates output vectors and multivariates output matrices.

**Comment by alexpghayes** [comment]
Punting on this since the project has switched into maintenance mode largely.
