### ISSUE TITLE
Distributions with multiple parameterizations

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#7]
Should we support all of them? Some of them? One of them?

Any and all takes appreciated here

For example: which geometric distribution should we use: https://en.wikipedia.org/wiki/Geometric_distribution? One? The other? Both?

Another example is the gamma distribution and whether or not to use the rate or the scale parameterization.

**Comment by EmilHvitfeldt** [comment]
My initial thought is to allow for all of them and convert under the hood (maybe even store all copies so users can see what the transformed parameter is). This way the user will be able to follow along with their textbook of choice with minimal resistance.

**Comment by alexpghayes** [comment]
I like. What do you think it should look like to construct `geometric()` and `gamma()` objects?

**Comment by alexpghayes** [comment]
The T distribution has me stumped as well

**Comment by EmilHvitfeldt** [comment]
For the gamma distribution [wikipedia](https://en.wikipedia.org/wiki/Gamma_distribution) lists the following 3 parameterizations

1. With a shape parameter k and a scale parameter θ.
2. With a shape parameter α = k and an inverse scale parameter β = 1/θ, called a rate parameter.
3. With a shape parameter k and a mean parameter μ = kθ = α/β.

the shape parameter is the same between the 3 so that can stay the same, then we just calculate the remaining 2 parameters depending on which is given with a hierarchy if multiple is specified. In this case I specify scale > rate > mean.

```r
gamma <- function(shape, scale = NULL, rate = NULL, mean = NULL) {
  
  # We can make this prettier later
  if (!is.null(scale)) {
    rate <- 1 / scale
    mean <- shape * scale
  } else if (!is.null(rate)) {
    scale <- 1 / rate
    mean <- shape / rate
  } else if (!is.null(mean)) {
    scale <- mean / shape
    rate <- shape / mean
  }
  
  d <- list(shape = shape, 
            scale = scale,
            rate = rate,
            mean = mean)
  class(d) <- "gamma"
  d
}
```

using this we include all the parameters.

```r
gamma(shape = 4, scale = 2)
#> $shape
#> [1] 4
#> 
#> $scale
#> [1] 2
#> 
#> $rate
#> [1] 0.5
#> 
#> $mean
#> [1] 8
#> 
#> attr(,"class")
#> [1] "gamma"
gamma(shape = 4, rate = 0.5)
#> $shape
#> [1] 4
#> 
#> $scale
#> [1] 2
#> 
#> $rate
#> [1] 0.5
#> 
#> $mean
#> [1] 8
#> 
#> attr(,"class")
#> [1] "gamma"
gamma(shape = 4, mean = 8)
#> $shape
#> [1] 4
#> 
#> $scale
#> [1] 2
#> 
#> $rate
#> [1] 0.5
#> 
#> $mean
#> [1] 8
#> 
#> attr(,"class")
#> [1] "gamma"
```

Since rate is maintained everything else should still work.

```r
distributions::random(gamma(shape = 4, scale = 2), 10)
#>  [1]  6.587824 12.388726 10.480415  4.470608  5.025457  7.425913 12.272745
#>  [8]  7.850094  5.665155  6.236660
```

Lastly we need to update the printing and I would suggest just listing all the parametizations.

```r
print.gamma <- function(x, ...) {
  cat(glue("Gamma distribution",
           "Parameterization 1: (shape = {x$shape}, scale = {x$scale})",
           "Parameterization 2: (shape = {x$shape}, rate = {x$rate})",
           "Parameterization 3: (shape = {x$shape}, mean = {x$mean})",
           .sep = "\n"))
}

gamma(shape = 4, scale = 2)
#> Gamma distribution
#> Parameterization 1: (shape = 4, scale = 2)
#> Parameterization 2: (shape = 4, rate = 0.5)
#> Parameterization 3: (shape = 4, mean = 8)
```

**Comment by 1danjordan** [comment]
Listing all the parameterisations would be very confusing. I think it should either print the parameter passed into the constructor or choose one as convention.

**Comment by alexpghayes** [comment]
Punting and closing, see comment in #20
