### ISSUE TITLE
Add is_discrete() method

### ISSUE THREAD

**Issue by alexpghayes** [alexpghayes/distributions3#76]
So that we can factor it out of other code, in particular for plotting. Should use `inherits()` instead of current `class(x)[1]` approach to be robust to future changes to the class system.

**Comment by zeileis** [comment]
I think this is a good idea and would be willing to have a look at it.

Any thoughts on how to deal with mixed discrete-continuous distributions, e.g., a normal distribution censored at zero (as in a tobit model).

**Comment by zeileis** [comment]
I have thought about this some more. One way to go about this would be to add both `is_discrete()` AND `is_continuous()` so that we don't have to assume that every distribution that is not fully discrete must be fully continuous and vice versa.

Then, the question remains what the two functions should return in case of a mixed distribution that has some point masses (often on one or both of the limits of the support) but also some continuous intervals. One could argue in either one of the following ways:

* _Both_ `is_discrete` and `is_continuous` should be `TRUE` because the distribution has both properties on certain subsets.
* _Neither_ `is_discrete` nor `is_continous` should be `TRUE` because the distribution has neither property on the entire support.

I lean towards the latter. Not because it makes more sense from a probability theory point of view but because it is more defensive in the implementation. I would expect that it reduces the risk if getting bitten by only checking `if(is_discrete)` and not also `!is_continuous` for example.

But if there are better ideas or arguments I would be happy to hear about it (and willing to work on it in terms of implementation).

**Comment by zeileis** [comment]
I think this issue can now be closed after https://github.com/alexpghayes/distributions3/pull/90 has been merged. Or is there anything left to do?
